apiVersion: node.k8s.io/v1
kind: Pod
metadata: 
  labels: 
    run: testpod 
  name: testpod
spec: 
  runtimeClassName: testclass
  containers:
  - image: nginx
    name: testpod
  dnsPolicy: ClusterFirst